<html>
<body>
<form method="post" action="/signUp">
    <label for="first-name">First Name
        <input class="input-field" type="text" id="first-name" name="firstName">
    </label>
    <label for="last-name">Last Name
        <input class="input-field" type="text" id="last-name" name="lastName">
    </label>
    <label for="login">Login
        <input class="input-field" type="text" id="login" name="login">
    </label>
    <label for="password">Password
        <input class="input-field" type="password" id="password" name="password">
    </label>
    <input type="submit" value="Sign Up">
</form>
</body>
</html>